baseURL: "https://inferara.com/"
languageCode: "en-us"
title: "Inferara"
theme: "PaperMod"

params:
  label:
    # icon: "images/logo.svg"
    defaultTheme: light
    # disableThemeToggle: true
    # # defaultTheme: dark
    # # defaultTheme: auto # to switch between dark or light according to browser theme

  profileMode:
    enabled: true
    subtitle: "We prove theorems to safeguard the open economy."
    imageUrl: "images/logo.svg"
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

