baseURL: "https://inferara.com/"
languageCode: "en-us"
title: "Inferara"
theme: "PaperMod"

params:
  label:
    # icon: "images/logo.svg"

  profileMode:
    enabled: true
    subtitle: "Prove code correctness with automated deduction"
    imageUrl: "images/logo.svg"
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

