baseURL: "https://inferara.com/"
languageCode: "en-us"
title: "Inferara"
theme: "PaperMod"
favicon: "favicon.ico"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

params:

  disableThemeToggle: true
  defaultTheme: light
  displayFullLangName: true

  label:
    icon: "images/logo.svg"
    # defaultTheme: dark
    # # defaultTheme: auto # to switch between dark or light according to browser theme

  profileMode:
    enabled: true
    imageUrl: "images/logo.svg"
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

assets:
  favicon16x16: "/assets/favicon-16x16.png"
  favicon32x32: "/assets/favicon-32x32.png"
  apple_touch_icon: "/assets/apple-touch-icon.png"
  android_chrome_192x192: "/assets/android-chrome-192x192.png"
  android_chrome_512x512: "/assets/android-chrome-512x512.png"

services:
  googleAnalytics:
    ID: G-HFSPPHXC3W

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
      parser:
          attribute:
            block: true
      renderer:
          unsafe: true

languages:
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Inferara
    weight: 1
    params:
      FooterSubtitle: '"If you do not do design right from the beginning, then every piece of the code you write is a patch. And you start out from the day 1 with a mess." – Leslie Lamport'
      profileMode:
        enabled: true
        title: "We do research in formal methods<br/>for protecting #Web3 digital assets<br/>and its citizens."
        subtitle: "Our goal is to make Web3 safe and secure environment for everyone<br/>with our experience in science and engineering."
        buttons:
          - name: Read Our Papers
            url: "/en/papers"
      socialIcons:
        - name: "X"
          url: "https://www.x.com/Inferara_kk"
        - name: "email"
          url: "mailto:info@inferara.com"
        - name: "github"
          url: "https://www.github.com/inferara"
        - name: "telegram"
          url: "https://t.me/inferara"
        - name: "discord"
          url: "https://discord.gg/GTybPMG2"
  jp:
    contentDir: content/jp
    disabled: false
    languageCode: ja-JP
    languageDirection: ltr
    languageName: 日本語
    title: インフェララ
    weight: 2
    params:
      FooterSubtitle: "「最初から設計を正しく行わないと、書くコードのすべてが継ぎ接ぎだらけになります。そして、初日から混乱した状態でスタートすることになります。」 - レスリー・ランポート"
      profileMode:
        enabled: true
        title: "Inferaraは、#Web3のデジタル資産と<br/>デジタル市民を守るために<br/>フォーマルな手法で研究を行っています。"
        subtitle: "Inferaraの目標は、科学技術の知見に基づき、<br/>Web3を全ての人々が安心できる安全な環境にすることです。"
        buttons:
          - name: 論文を読む
            url: "/jp/papers"
      socialIcons:
        - name: "X"
          url: "https://www.x.com/Inferara_kk"
        - name: "email"
          url: "mailto:info@inferara.com"
        - name: "github"
          url: "https://www.github.com/inferara"
        - name: "telegram"
          url: "https://t.me/inferara"
        # - name: "line"
        #   url: "https://line.me/ti/p/~inferara"
        - name: "discord"
          url: "https://discord.gg/GTybPMG2"
